In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [92]:
data_url = 'https://raw.githubusercontent.com/Customer-Churn-Prediction/Project-Machine-Learning/master/Churning.csv'
data = pd.read_csv(data_url)
data.head()

Account Length  VMail Message  Day Mins  Eve Mins  Night Mins  Intl Mins  \
0             128             25     265.1     197.4       244.7       10.0   
1             107             26     161.6     195.5       254.4       13.7   
2             137              0     243.4     121.2       162.6       12.2   
3              84              0     299.4      61.9       196.9        6.6   
4              75              0     166.7     148.3       186.9       10.1   

   CustServ Calls  Churn  Int'l Plan  VMail Plan    ...     Day Charge  \
0               1      0           0           1    ...          45.07   
1               1      0           0           1    ...          27.47   
2               0      0           0           0    ...          41.38   
3               2      0           1           0    ...          50.90   
4               3      0           1           0    ...          28.34   

   Eve Calls  Eve Charge  Night Calls  Night Charge  Intl Calls  Intl Charge  \
0         99       16.78           91         11.01           3         2.70   
1        103       16.62          103         11.45           3         3.70   
2        110       10.30          104          7.32           5         3.29   
3         88        5.26           89          8.86           7         1.78   
4        122       12.61          121          8.41           3         2.73   

   State Area Code     Phone  
0     KS       415  382-4657  
1     OH       415  371-7191  
2     NJ       415  358-1921  
3     OH       408  375-9999  
4     OK       415  330-6626  

[5 rows x 21 columns]

In [93]:
target = np.array(data.Churn)
data = data.drop(['Churn', 'Phone'], axis=1)
data.head()

Account Length  VMail Message  Day Mins  Eve Mins  Night Mins  Intl Mins  \
0             128             25     265.1     197.4       244.7       10.0   
1             107             26     161.6     195.5       254.4       13.7   
2             137              0     243.4     121.2       162.6       12.2   
3              84              0     299.4      61.9       196.9        6.6   
4              75              0     166.7     148.3       186.9       10.1   

   CustServ Calls  Int'l Plan  VMail Plan  Day Calls  Day Charge  Eve Calls  \
0               1           0           1        110       45.07         99   
1               1           0           1        123       27.47        103   
2               0           0           0        114       41.38        110   
3               2           1           0         71       50.90         88   
4               3           1           0        113       28.34        122   

   Eve Charge  Night Calls  Night Charge  Intl Calls  Intl Charge State  \
0       16.78           91         11.01           3         2.70    KS   
1       16.62          103         11.45           3         3.70    OH   
2       10.30          104          7.32           5         3.29    NJ   
3        5.26           89          8.86           7         1.78    OH   
4       12.61          121          8.41           3         2.73    OK   

   Area Code  
0        415  
1        415  
2        415  
3        408  
4        415

In [104]:
train_x, test_x, train_y, test_y = train_test_split(data, target, test_size=0.3, random_state=42)                                            

In [106]:
print(len(test_x))
print(len(train_x))

1000
2333


In [107]:
features = data.columns[:17]
len(features)

17

In [116]:
clf = RandomForestClassifier(n_jobs = -1)
clf.fit(train_x[features], train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [109]:
pred = clf.predict(test_x[features])
pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0,

In [110]:
clf.predict_proba(test_x[features])[0:14]

array([[ 0.7,  0.3],
       [ 1. ,  0. ],
       [ 0.2,  0.8],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       [ 1. ,  0. ],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       [ 1. ,  0. ],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       [ 0.1,  0.9]])

In [111]:
from sklearn.metrics import confusion_matrix

In [112]:
cnf_mat = confusion_matrix(test_y, pred)
cnf_mat

array([[852,   5],
       [ 57,  86]], dtype=int64)

In [113]:
pd.crosstab(test_y, pred, rownames=['Actual Churn'], colnames=['Predicted Churn'])

Predicted Churn    0   1
Actual Churn            
0                852   5
1                 57  86

In [114]:
list(zip(train_x[features], clf.feature_importances_))

[('Account Length', 0.022364291551640547),
 ('VMail Message', 0.029694286859543818),
 ('Day Mins', 0.1456462627493528),
 ('Eve Mins', 0.074620036399983977),
 ('Night Mins', 0.033084449955396666),
 ('Intl Mins', 0.037243589024321948),
 ('CustServ Calls', 0.10109671185632511),
 ("Int'l Plan", 0.078973009339967801),
 ('VMail Plan', 0.027555778010768854),
 ('Day Calls', 0.03684841813930171),
 ('Day Charge', 0.13604159891815462),
 ('Eve Calls', 0.026376052563051516),
 ('Eve Charge', 0.072481748264215079),
 ('Night Calls', 0.029420657054484711),
 ('Night Charge', 0.046305211133422085),
 ('Intl Calls', 0.049443536372597588),
 ('Intl Charge', 0.052804361807471153)]

In [115]:
plt.bar(train_x.State.groupby(), np.array(train_y))
plt.show()

TypeError: You have to supply one of 'by' and 'level'